stages:          # List of stages for jobs, and their order of execution
  - style

workflow:
  rules:
    # skip running branch pipelines if a MR is open for the branch
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

check_style:       # This job runs in the build stage, which runs first.
  stage: style
  rules:
    # always run the style check on any push event
    - if: $CI_PIPELINE_SOURCE == "push"
    - when: on_success
  script:
    - echo "Checking tabs..."
    - .github/workflows/style/check_tabs.sh
    - echo "Checking EOL whitespaces..."
    - .github/workflows/style/check_trailing_whitespaces.sh